### PR TITLE
fix: error starting the app

### PR DESCRIPTION
**Pull request by dejimania**
Kindly review and merge. I fix module error that's prevent the app from running. 
Regards

### CODE REVIEW

**Review by Busry — COMMENTED** [review]
Good! but nodemon is part of devDependencies

**Review by Busry — APPROVED** [review]
Someone will correect that later

**Review by dinakajoy — APPROVED** [review]
Awesome

**Review by lutitech — APPROVED** [review]
nice but we need to change nodemon to dev dependencies

**Pull request merged**
